config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
    root :to => "devise/sessions#new"
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :posts do
    resources :comments
    resource :favorites, only: [:create, :destroy]
  end

  resources :books, only: [:show], param: :isbn do
    collection do
      get 'search'
      get 'rank'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        favorite = current_user.favorites.new(post_id: @post.id)
        favorite.save
        # redirect_to post_path(id: post.id, book_id: post.book.id)
    end
    def destroy
        @post = Post.find(params[:post_id])
        favorite = current_user.favorites.find_by(post_id: @post.id)
        favorite.destroy
        # redirect_to post_path(id: post.id, book_id: post.book.id)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if post.favorited_by?(current_user) %>
    <%= link_to post_favorites_path(post_id: post.id, book_id: post.book.id), method: :delete, remote: true, class: "favorite_btn" do %>
    ♥<%= post.favorites.count %> いいね
    <% end %>
<% else %>
    <%= link_to post_favorites_path(post_id: post.id, book_id: post.book.id), method: :post, remote: true, class: "favorite_btn" do %>
    ♡<%= post.favorites.count %> いいね
    <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_btn_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorite_btn_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");