config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
    root :to => "devise/sessions#new"
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :posts do
    resources :comments
    resource :favorites, only: [:create, :destroy]
  end

  resources :books, only: [:show], param: :isbn do
    collection do
      get 'search'
      get 'rank'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "管理者ゲスト"
      user.admin = "true"
    end
  end
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]
  # redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def ensure_normal_user
    if @user.name == 'ゲスト'|| @user.name == '管理者ゲスト'
      redirect_to posts_path, alert: 'ゲストユーザーの更新・削除はできません'
    end
  end
  # # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  # # アカウント編集後、プロフィール画面に移動する
  # def after_update_path_for(resource)
  #   user_path(id: current_user.id)
  # end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  def admin_guest_sign_in
    user = User.admin_guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザー(管理者)としてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_normal_user, only: %i[ update destroy]

  def index
    @users = User.page(params[:page]).per(20).reverse_order
    @users = @users.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
    @following_users = @user.following_user
    @follower_users = @user.follower_user

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image)
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_user.page(params[:page]).per(3).reverse_order
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.follower_user.page(params[:page]).per(3).reverse_order
  end
  
  def ensure_normal_user
    @user = User.find(params[:id])
    if @user.name == 'ゲスト'|| @user.name == '管理者ゲスト'
      redirect_to edit_user_path, alert: 'ゲストユーザーの更新・削除はできません'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% users.each do |user| %>
    <div class="media">
        <a class="pull-left" href="#">
            <p class="user-profile-image"><%= attachment_image_tag user, :profile_image, fallback: "no_profile_image.png", class: "mb-3 profile-img" %></p>
        </a>
        <div class="media-body">
            <%= link_to user_path(user) do %>
                <h4 class="media-heading"><%= user.name %></h4>
            <% end %>
            <%= user.profile %>
            <p class="caption"><%= "#{user.posts.count} 投稿" %></p>
            <hr class="my-4">
        </div>
    </div>
<% end %>
<div class="text-right">
    <%= paginate users %>
</div>

app/views/users/edit.html.erb
<div class="jumbotron">
    <h1 class="display-4">プロフィール編集!</h1>
    <hr class="my-4">
    <%= link_to "タイムライン", posts_path, class: "btn btn-warning btn-lg text-white" %>
</div>
<div class="container">
    <div class="content justify-content-center">
        <div class="book-card-list">
            <div class="text-center">   
                <div class="box-inner">
                <%= form_with model: @user, local:true do |f| %>
                    <div class="form-group">
                        <label class="form-label">名前</label>
                        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <label class="form-label">プロフィール画像</label><br>
                        <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_profile_image.png", class: "mb-3 profile-img" %><br>
                        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
                    </div>
                    <div class="form-group">
                        <label class="form-label">プロフィール</label>
                        <%= f.text_field :profile, class: "form-control" %><br>
                    </div>
                    <%= f.submit '保存する', class: "btn btn-success" %>
                <% end %>
                    <div class="box-newusr">
                    <% unless @user.name == 'ゲスト'|| @user.name == '管理者ゲスト'%>
                        <p><span>------------</span> Email・パスワード・アカウント削除 <span>------------</span></p>
                        <%= link_to "ユーザー情報", edit_user_registration_path, class: "btn btn-primary" %><br>
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/followers.html.erb
<div class="cover-user-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-5 mb-5">フォロワー一覧</h1>
    </div>
    <%= render 'form', users: @users, user: @user %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="cover-user-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-5 mb-5">フォロー一覧</h1>
    </div>
    <%= render 'form', users: @users, user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
    <h1 class="display-4">ユーザー一覧!</h1>
    <hr class="my-4">
    <%= link_to "タイムライン", posts_path, class: "btn btn-warning btn-lg text-white" %>
</div>
<div class="container">
    <div class="text-right mb-3">
        <%= form_with url: users_path, method: :get, local: true do |f| %>
            <%= f.text_field :search %>
            <%= f.submit '検索', name: nil, class: "btn btn-info" %>
        <% end %>
    </div>
    <%= render 'form', users: @users, user: @user %>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
    <% if user_signed_in? && @user == current_user %>
        <h1 class="display-4">マイページ</h1>
    <% else %>
        <h1 class="display-4"><%= @user.name %>さんのページ</h1>
    <% end %>
    <hr class="my-4">
    <%= link_to "タイムライン", posts_path, class: "btn btn-warning btn-lg text-white" %>
</div>
<div class="container">
    <div class="text-right">
        <% if user_signed_in? && @user == current_user %>
            <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn-sm btn-success" %><br>
        <% end %>
    </div>
    <div class="media">
        <a class="pull-left" href="#">
            <p class="user-profile-image"><%= attachment_image_tag @user, :profile_image, fallback: "no_profile_image.png", class: "mb-3 profile-img" %></p>
        </a>
        <div class="media-body">
            <%= link_to user_path(@user) do %>
                <h4 class="media-heading"><%= @user.name %></h4>
            <% end %>
            <%= @user.profile %>
            <p class="caption"><%= "#{@user.posts.count} 投稿" %></p>
            <hr class="my-4">
        </div>
    </div>
    <% if current_user != @user %>
        <% if current_user.following?(@user) %>
        <%= link_to 'フォロー外す', user_relationships_path(@user.id), method: :delete, class: "btn-sm btn-danger" %>
        <% else %>
        <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class:"btn-sm btn-success" %>
        <% end %>
    <% end %>
    <div class="display-flex">
        <%= link_to follows_user_path(@user) do %>
            <h6>フォロー<%= @following_users.count %></h6>
        <% end %>&nbsp;&nbsp;
        <%= link_to followers_user_path(@user) do %>
            <h6>フォロワー<%= @follower_users.count %></h6>
        <% end %>
    </div>
    <div class="d-flex justify-content-center">
            <h1 class="font-weight-normal mt-5 mb-5">これまでのレビュー</h1> 
        </div> 
    <div class="content">
        <div class="card-wrap">    
            <% @posts.each do |post| %>
                <div class="card">
                    <div class="card-header">
                    </div>
                    <div class="card-body">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <p class="book-image"><%= link_to (image_tag(post.book.image_url)), post.book.url %></p>
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="book-title"><%= post.book.title %></h5>
                                    <div id="star-rate-<%= post.id %>"></div>
                                        <script>
                                            $('#star-rate-<%= post.id %>').raty({
                                                size: 36,
                                                starOff:  '<%= asset_path('star-off.png') %>',
                                                starOn : '<%= asset_path('star-on.png') %>',
                                                starHalf: '<%= asset_path('star-half.png') %>',
                                                half: true,
                                                readOnly: true,
                                                score: <%= post.rate %>,
                                            });
                                        </script>
                                    <p class="review"><%= post.review %></p>
                                </div>
                            </div>
                        </div>
                    </div>  
                    <div class="card-footer">
                        <p class="card-text"><small class="text-muted"><%= post.created_at.strftime('%Y/%m/%d %H:%M') %></small></p>
                        <div id="favorite_btn_<%= post.id %>">
                            <%= render 'favorites/favorite', post: post %>
                        </div>
                        <%= "#{post.comments.count} コメント" %>
                        <div class="text-right ">   
                            <%= link_to "詳細", post_path(id: post.id, book_id: post.book.id ),  class: "btn btn-success" %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <div class="pagination justify-content-center">
        <%= paginate @posts %>
    </div>              
</div>