config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
    root :to => "devise/sessions#new"
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :posts do
    resources :comments
    resource :favorites, only: [:create, :destroy]
  end

  resources :books, only: [:show], param: :isbn do
    collection do
      get 'search'
      get 'rank'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/book.rb
class Book < ApplicationRecord
    has_many :posts, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def rank
    @books = []
      results = RakutenWebService::Books::Book.search({
        booksGenreId: "001004",
        # 漫画
        # booksGenreId: "001001",
        sort: "sales",
        hits: 10,
        outOfStockFlagoutOfStockFlag: 1
      })
      #@booksにAPIからの取得したJSONデータを格納
      results.each do |result|
        book = Book.new(read(result))
        @books << book
      end
  end
  
  def search
    @books = []
    @title = params[:title]
    if @title.present?
      results = RakutenWebService::Books::Book.search({
        title: @title,
        hits: 20,
        outOfStockFlagoutOfStockFlag: 1
      })

      #@booksにAPIからの取得したJSONデータを格納
      results.each do |result|
        book = Book.new(read(result))
        @books << book
      end
    end
  end
  

  def show
    @book = Book.find_or_initialize_by(isbn: params[:isbn])
    results = RakutenWebService::Books::Book.search(isbn: @book.isbn)
    @book = Book.new(read(results.first))
  end




  
  private
  #「楽天APIのデータから必要なデータを絞り込む」、且つ「対応するカラムにデータを格納する」メソッドを設定していきます。
  # result内のキャメル型の情報を通常のハッシュ型に戻す
  def read(result)
    title = result["title"]
    author = result["author"]
    publishername = result["publisherName"]
    url = result["itemUrl"]
    isbn = result["isbn"]
    image_url = result["largeImageUrl"]
    item_caption = result["itemCaption"]
    {
      title: title,
      author: author,
      publishername: publishername,
      url: url,
      isbn: isbn,
      image_url: image_url,
      item_caption: item_caption
    }
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/rank.html.erb
<div class="jumbotron">
    <h1 class="display-4">⭐️Trend⭐️!</h1>
    <p class="lead">楽天ブックス売上ランキング　TOP 10！</p>
    <hr class="my-4">
    <%= link_to "タイムラインに戻る", posts_path, class: "btn btn-warning btn-lg text-white" %>
</div>
<div class="container">
    <div class="content">
        <div class="card-wrap">
            <% if @books.present? %>
                <% @books.each do |book| %>
                <div class="card"> 
                    <div class="card-body">
                        <div class="row g-0">
                            <div class="col-md-4">         
                                <p class="book-image"><%= link_to (image_tag(book.image_url)), book.url %></p>
                            </div>
                            <div class="card-body">
                                <p class="book-title">タイトル：<%= book.title %></p>
                                <hr class="my-３">
                                <p class="book-author">著者/編集：<%= book.author %></p>
                                <hr class="my-３">
                                <p class="book-publisherName">出版社：<%= book.publishername %></p>
                                <hr class="my-３">
                                <p class="book-itemCaption">内容紹介：<%= book.item_caption %></p>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-right ">   
                            <%= link_to "詳細へ", book_path(isbn: book.isbn),  class: "btn btn-success" %><br>
                        </div>
                    </div>  
                </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/books/search.html.erb
<div class="jumbotron">
    <h1 class="display-4">検索結果!</h1>
    <hr class="my-4">
    <%= link_to "タイムライン", posts_path, class: "btn btn-warning btn-lg text-white" %>
</div>
<div class="container">
    <div class="content">
        <div class="card-wrap">
            <% if @books.present? %>
                <% @books.each do |book| %>
                <div class="card"> 
                    <div class="card-body">
                        <div class="row g-0">
                            <div class="col-md-4">         
                                <p class="book-image"><%= link_to (image_tag(book.image_url)), book.url %></p>
                            </div>
                            <div class="card-body">
                                <p class="book-title">タイトル：<%= book.title %></p>
                                <hr class="my-３">
                                <p class="book-author">著者/編集：<%= book.author %></p>
                                <hr class="my-３">
                                <p class="book-publisherName">出版社：<%= book.publishername %></p>
                                <hr class="my-３">
                                <p class="book-itemCaption">内容紹介：<%= book.item_caption %></p>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-right ">   
                            <%= link_to "詳細へ", book_path(isbn: book.isbn),  class: "btn btn-success" %><br>
                        </div>
                    </div>  
                </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="jumbotron">
    <h1 class="display-4">書籍情報!</h1>
    <p class="lead">タイトル・著者・内容紹介などが確認できます！</p>
    <hr class="my-4">
    <%= link_to "戻る", :back, class: "btn btn-secondary btn-lg text-white" %>
</div>
<div class="container">
    <div class="content justify-content-center">
        <div class="book-card-list">
            <p class="book-image"><%= link_to (image_tag(@book.image_url)), @book.url %></p>
            <p class="book-title">タイトル：<%= @book.title %></p>
            <hr class="my-３">
            <p class="book-author">著者/編集：<%= @book.author %></p>
            <hr class="my-３">
            <p class="book-publisherName">出版社：<%= @book.publishername %></p>
            <hr class="my-３">
            <p class="book-itemCaption">内容紹介：<%= @book.item_caption %></p>
            <%= link_to "レビューを作成する", new_post_path(isbn: @book.isbn),  class: "btn btn-success" %><br>
        </div>
    </div>
</div>